### ISSUE TITLE
Feedback When Adding to Encounter

### ISSUE THREAD

**Issue by spencerkordecki** [gthayer/monster-manager#1]
Found this on r/dnd, nice job! 

Just wanted to add a feature request here to have some feedback when adding a monster to an encounter since currently nothing happens and you can end up adding multiple monsters to the campaign without ever realizing it.

**Comment by gthayer** [comment]
Thanks for the feedback! Something I'll definitely add.

**Comment by gthayer** [comment]
Thanks again! I've added some animation to the button's hover/active states. There is also now a counter in the top right which tracks total monsters in encounter.
