### ISSUE TITLE
How was the monsters.js data gathered?

### ISSUE THREAD

**Issue by alexjgustafson** [gthayer/monster-manager#2]
Just curious how the monsters.js data was gathered? Surely no one just typed out the monster manual by hand?

**Comment by gthayer** [comment]
This is the original reddit thread I got the content from: https://www.reddit.com/r/dndnext/comments/43a09o/srd_monsters_in_json_format/

The data is from the SRD, so not all creatures in the Monster Manuel are included, only those they've open sourced.

**Comment by alexjgustafson** [comment]
Thanks!
